// Code generated by "stringer -type=Flags"; DO NOT EDIT.

package flags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FNone-1]
	_ = x[FPrimary-2]
	_ = x[FSecondary-4]
	_ = x[FHome-8]
	_ = x[FWork-16]
}

const (
	_Flags_name_0 = "FNoneFPrimary"
	_Flags_name_1 = "FSecondary"
	_Flags_name_2 = "FHome"
	_Flags_name_3 = "FWork"
)

var (
	_Flags_index_0 = [...]uint8{0, 5, 13}
)

func (i Flags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Flags_name_0[_Flags_index_0[i]:_Flags_index_0[i+1]]
	case i == 4:
		return _Flags_name_1
	case i == 8:
		return _Flags_name_2
	case i == 16:
		return _Flags_name_3
	default:
		return "Flags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
