// Code generated by "stringer -type=PhoneFlags"; DO NOT EDIT.

package flags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PFMobile-1]
}

const _PhoneFlags_name = "PFMobile"

var _PhoneFlags_index = [...]uint8{0, 8}

func (i PhoneFlags) String() string {
	i -= 1
	if i >= PhoneFlags(len(_PhoneFlags_index)-1) {
		return "PhoneFlags(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PhoneFlags_name[_PhoneFlags_index[i]:_PhoneFlags_index[i+1]]
}
